name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          :tada: Welcome to the project, @${{ github.actor }}! :tada:
          Thank you for opening your first issue! We're excited to have you contribute to this project. If you need any help or have questions, feel free to ask. We're here to help!
        pr-message: |
          :tada: Welcome to the project, @${{ github.actor }}! :tada:
          Thank you for your first pull request! We're thrilled to see you contributing. Please make sure to follow the contributing guidelines, and don't hesitate to reach out if you need any assistance. We're here to support you!
