# This is the name of the workflow
name: PR Audit

# It will run whenever a Pull Request is opened
on: [pull_request]

jobs: 
  lint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the PR code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python (v3.11)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install tools (flake8, black, isort)
      - name: Install tools
        run: |
          pip install flake8 black isort

      # Step 4: Linting with flake8 and commenting via reviewdog
      - name: Run flake8 for linting
        uses: reviewdog/action-flake8@v3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
          fail_on_error: true
          filter_mode: diff_context

      # Step 5: Check formatting with black
      - name: Run black
        run: black . -check

      # Step 6: Check import sorting with isort
      - name: Run isort
        run: isort . --check-only
